/**
* This header is generated by class-dump-z 0.2a.
* class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
*
* Source: (null)
*/


typedef struct _NSZone NSZone;

typedef struct {
BOOL _field1;
BOOL _field2;
BOOL _field3;
BOOL _field4;
float _field5;
int _field6;
} XXStruct_3uUjXA;


typedef struct __GSEvent* GSEventRef;


typedef struct __darwin_pthread_handler_rec darwin_pthread_handler_rec;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct _MISProfile* MISProfileRef;

typedef struct {
unsigned _field1[8];
} XXStruct_kUSYWB;

typedef struct {
int _field1;
int _field2;
} XXStruct_K5nmsA;

typedef struct __CTServerConnection* CTServerConnectionRef;

typedef struct __CTCall* CTCallRef;

typedef struct __WiFiManagerClient WiFiManagerClient;

typedef struct __WiFiDeviceClient WiFiDeviceClient;

typedef struct __WiFiNetwork WiFiNetwork;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct dispatch_source_s dispatch_source_s;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct __CFBundle* CFBundleRef;

typedef struct __CFMachPort* CFMachPortRef;

typedef struct dispatch_group_s dispatch_group_s;

typedef struct SBProcessTimes {
double execTime;
double beginUserCPUElapsedTime;
double beginSystemCPUElapsedTime;
double beginIdleCPUElapsedTime;
double beginApplicationCPUElapsedTime;
} SBProcessTimes;

typedef struct {
int direction;
CGRect rect;
} XXStruct_9ihRqB;

typedef struct {
int type;
unsigned pathIndex;
CGPoint location;
CGPoint previousLocation;
float totalDistanceTraveled;
int interfaceOrientation;
int previousInterfaceOrientation;
} XXStruct_DSYOgA;

typedef struct __SBGestureContext* SBGestureContextRef;

typedef struct CGContext* CGContextRef;



